Experience with a certain type of plastic indicates that a relation exists between the hardness (measured in Brinell units) of items molded from the plastic (Y) and the elapsed time since termination of the molding process (X). It is proposed to study this relation by means of regression analysis. A participant in the discussion objects, pointing out that the hardening of the plastic “is the result of a natural chemical process that doesn’t leave anything to chance, so the relation must be mathematical and regression analysis is not appropriate.” Evaluate this objection.

Sixteen batches of the plastic were made, and from each batch one test item was molded. Each test item was randomly assigned to one of the four predetermined time levels, and the hardness was measured after the assigned elapsed time. The results are shown below; X is the elapsed time in hours, and Y is hardness in Brinell units. Assume that first-order regression model is appropriate.

|Time(X) |Hardness (Y) |
|---|-- |
|16 |199|
|16	|205|
|16	|196|
|16	|200|
|24	|218|
|24	|220|
|24	|215|
|24	|223|
|32	|237|
|32	|234|
|32	|235|
|32	|230|
|40	|250|
|40	|248|
|40	|253|
|40	|246|

In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data =np.matrix([[16,199], [16,205], [16,196], [16,200], [24,218], [24,220], 
             [24,215], [24,223], [32,237],[32,234], [32,235], [32,230],
             [40,250], [40,248], [40,253], [40,246]])
data.shape

(16, 2)

In [3]:
ones = np.ones((16,1))
data = np.append(data, ones, axis=1)
data

matrix([[ 16., 199.,   1.],
        [ 16., 205.,   1.],
        [ 16., 196.,   1.],
        [ 16., 200.,   1.],
        [ 24., 218.,   1.],
        [ 24., 220.,   1.],
        [ 24., 215.,   1.],
        [ 24., 223.,   1.],
        [ 32., 237.,   1.],
        [ 32., 234.,   1.],
        [ 32., 235.,   1.],
        [ 32., 230.,   1.],
        [ 40., 250.,   1.],
        [ 40., 248.,   1.],
        [ 40., 253.,   1.],
        [ 40., 246.,   1.]])

In [4]:
X = data[:,[2,0]] 
X

matrix([[ 1., 16.],
        [ 1., 16.],
        [ 1., 16.],
        [ 1., 16.],
        [ 1., 24.],
        [ 1., 24.],
        [ 1., 24.],
        [ 1., 24.],
        [ 1., 32.],
        [ 1., 32.],
        [ 1., 32.],
        [ 1., 32.],
        [ 1., 40.],
        [ 1., 40.],
        [ 1., 40.],
        [ 1., 40.]])

In [5]:
Y = data[:,1]
Y

matrix([[199.],
        [205.],
        [196.],
        [200.],
        [218.],
        [220.],
        [215.],
        [223.],
        [237.],
        [234.],
        [235.],
        [230.],
        [250.],
        [248.],
        [253.],
        [246.]])

In [6]:
#Find Y'Y
np.transpose(Y).dot(Y)

matrix([[819499.]])

In [7]:
#Find X'X
np.transpose(X).dot(X)

matrix([[   16.,   448.],
        [  448., 13824.]])

In [8]:
#Find X'Y
np.transpose(X).dot(Y)

matrix([[  3609.],
        [103656.]])

The normal error regression model in matrix terms is $\underset{n x 1}{Y} = \underset{n x 2}{X} \; \underset{2 x 1}{\beta}  +\underset{nx1}{\epsilon} $ where

$\underset{n x 1}{Y} = \begin{pmatrix} Y_{1}\\ Y_{2}\\ Y_{3}\\ \cdots\\ \cdots\\ Y_{n}\\ \end{pmatrix}$  $\;$  $\underset{n x 2}{X} = \begin{pmatrix} 1 & X_{1}\\1 & X_{2}\\ 1 & X_{3}\\ 1&\cdots\\ 1&\cdots\\ 1 & X_{n}\\ \end{pmatrix}$  $\;$   $\underset{2 x 1}{\beta} = \begin{pmatrix} \beta_{0}\\ \beta{1}\end{pmatrix}$ $\;$     $\underset{nx1}{\epsilon} = \begin{pmatrix} \epsilon_{1}\\ \epsilon_{2}\\ \epsilon_{3}\\ \cdots\\ \cdots\\ \epsilon_{n}\\ \end{pmatrix}$ 

Here $\epsilon$ is a vector of independent normal random variables with $E\{\epsilon\}=0$ and $\sigma^2\{\epsilon\}=\sigma^2I$. 



$\begin{pmatrix} Y_{1}\\ Y_{2}\\ Y_{3}\\ \cdots\\ \cdots\\ Y_{n}\\ \end{pmatrix} =$ $\begin{pmatrix} \beta_{0} + \beta_{1}X_{1}\\ \beta_{0} + \beta_{1}X_{2}\\\beta_{0} + \beta_{1}X_{3}\\ \cdots  \cdots\\ \cdots  \cdots\\  \beta_{0} + \beta_{1}X_{n}\end{pmatrix} +$ $\begin{pmatrix} \epsilon_{1}\\ \epsilon_{2}\\ \epsilon_{3}\\ \cdots\\ \cdots\\ \epsilon_{n}\\ \end{pmatrix} =$ $\begin{pmatrix} \beta_{0} + \beta_{1}X_{1} + \epsilon_{1}\\ \beta_{0} + \beta_{1}X_{2} +\epsilon_{2}\\\beta_{0} + \beta_{1}X_{3}+\epsilon_{3}\\ \cdots  \cdots\\ \cdots  \cdots\\  \beta_{0} + \beta_{1}X_{n} +\epsilon_{n}\end{pmatrix}$

The matrix above is often long and skinny in the linear regression case and therefore the matrix is inconsistent, otherwise a consistent matrix would be reduceable and a straight line would intersect each point. Multiplying $A^{T}$ to $A$ creates a square iinversable matrix, which is then inversed. All manipulations on the LHS must be balanced on the RHS. To isolate $x$ in $Ax=b$ we'd use matrix manipulation to find the equation $\hat{x}\ =\ \left(A^TA\right)^{-1}A^T\bar{b}$ 

## Use matrix methods to obtain $(X'X)^{-1}$

In [9]:
np.linalg.inv(X.T @ X)

matrix([[ 0.675     , -0.021875  ],
        [-0.021875  ,  0.00078125]])

## Use matrix methods to obtain $b = (X'X)^{-1}X'Y$

In [10]:
b = np.linalg.inv(X.T @ X)@np.transpose(X)@Y
b

matrix([[168.6     ],
        [  2.034375]])

## Use matrix methods to find $\hat{Y}$

In [11]:
y_hat = X.dot(b)
y_hat

matrix([[201.15 ],
        [201.15 ],
        [201.15 ],
        [201.15 ],
        [217.425],
        [217.425],
        [217.425],
        [217.425],
        [233.7  ],
        [233.7  ],
        [233.7  ],
        [233.7  ],
        [249.975],
        [249.975],
        [249.975],
        [249.975]])

## Find H using matrix methods

In [12]:
#Use matrix methods to find H = X(X'X)^-1X'
step1 = X.T.dot(X)
step2 = np.linalg.inv(step1)
step3 = X.dot(step2)
H = step3.dot(X.T)
H

matrix([[ 0.175,  0.175,  0.175,  0.175,  0.1  ,  0.1  ,  0.1  ,  0.1  ,
          0.025,  0.025,  0.025,  0.025, -0.05 , -0.05 , -0.05 , -0.05 ],
        [ 0.175,  0.175,  0.175,  0.175,  0.1  ,  0.1  ,  0.1  ,  0.1  ,
          0.025,  0.025,  0.025,  0.025, -0.05 , -0.05 , -0.05 , -0.05 ],
        [ 0.175,  0.175,  0.175,  0.175,  0.1  ,  0.1  ,  0.1  ,  0.1  ,
          0.025,  0.025,  0.025,  0.025, -0.05 , -0.05 , -0.05 , -0.05 ],
        [ 0.175,  0.175,  0.175,  0.175,  0.1  ,  0.1  ,  0.1  ,  0.1  ,
          0.025,  0.025,  0.025,  0.025, -0.05 , -0.05 , -0.05 , -0.05 ],
        [ 0.1  ,  0.1  ,  0.1  ,  0.1  ,  0.075,  0.075,  0.075,  0.075,
          0.05 ,  0.05 ,  0.05 ,  0.05 ,  0.025,  0.025,  0.025,  0.025],
        [ 0.1  ,  0.1  ,  0.1  ,  0.1  ,  0.075,  0.075,  0.075,  0.075,
          0.05 ,  0.05 ,  0.05 ,  0.05 ,  0.025,  0.025,  0.025,  0.025],
        [ 0.1  ,  0.1  ,  0.1  ,  0.1  ,  0.075,  0.075,  0.075,  0.075,
          0.05 ,  0.05 ,  0.05 ,  0.05 ,  0.0

## Find SSE and MSE

In [13]:
#Find SSE, Q, when Q = Y'Y-Beta'X'Y - Y'XBeta + Beta'X'XBeta
S1 = Y.T.dot(Y)
S2 = S1 - b.T.dot(X.T).dot(Y)
S3 = S2 - Y.T.dot(X).dot(b)
S4 = S3 + b.T.dot(X.T).dot(X).dot(b)

def SSE_func(X,Y,Beta):
    f= Y.T.dot(Y)-Beta.T.dot(X.T).dot(Y) - Y.T.dot(X).dot(b) + b.T.dot(X.T).dot(X).dot(b)
    return f[0,0]

def MSE_func(X,Y,Beta):
    z= Y.T.dot(Y)-Beta.T.dot(X.T).dot(Y) - Y.T.dot(X).dot(b) + b.T.dot(X.T).dot(X).dot(b)
    f= z/(len(X)-2)
    return f[0,0]
    

In [14]:
SSE = SSE_func(X,Y,b)
SSE

146.42500000004657

In [15]:
MSE = MSE_func(X,Y,b)
MSE

10.458928571431898

## Find $ \sigma^{2} \left \{ b \right \}$

The variance-covariance matrix of b is   $ \sigma^{2} \left \{ b \right \} = \begin{bmatrix}
\sigma^{2} \left \{ b_{0} \right \} & \sigma \left \{ b_{0}, b_{1} \right \}  \\ 
\sigma \left \{ b_{1}, b_{0} \right \}  & \sigma^{2} \left \{ b_{1} \right \} 
\end{bmatrix} $ also as$\hspace{1 mm}$  $ \sigma^{2} \left \{ b \right \} = \sigma \left(X'X^{-1} \right)$. Substituting MSE for $\sigma^{2}$ gives the estimated variance-covariance matrix for $b$,denoted by $s^{2}\left\{ b \right\}$.

In [16]:
#find s^2(b) 
s_2b = MSE*np.linalg.inv(X.T.dot(X))
s_2b

matrix([[ 7.05977679, -0.22878906],
        [-0.22878906,  0.00817104]])

Now, $s^{2}\left \{ b_{0} \right \}$=

In [17]:
s_2b[0,0]

7.059776785716535

And, $s^{2}\left \{ b_{1} \right \}$=

In [18]:
s_2b[1,1]

0.008171037946431176

## Estimate the mean response of a new observation when $X_{h}=30$

$s^{2}\left \{ pred \right \} = MSE(1 + X_{h}^{'} (X'X)^{-1}X_{h}) $

In [19]:
new = np.matrix([1,30])

In [20]:
s2_pred= MSE*(1+new * np.linalg.inv(X.T.dot(X)) * new.T)
s2_pred

matrix([[11.14529576]])

## Find $s^{2}\left \{ b_{0} \right \}$, $s\left \{ b_{0},b_{1} \right \}$ and $s\left \{ b_{1} \right \}$

In [21]:
#s^2{b0}
s_2b[0,0]

7.059776785716535

In [22]:
#s{b_0,b1}
s_2b[0,1]

-0.2287890625000729

In [23]:
#s{b_1}
np.sqrt(s_2b[1,1])

0.09039379373845959

## Obtain the matrix of the quadratic form for SSE.

$SSE = Y'(I-H)Y$

In [36]:
np.identity(H.shape[0])-H

matrix([[ 0.825, -0.175, -0.175, -0.175, -0.1  , -0.1  , -0.1  , -0.1  ,
         -0.025, -0.025, -0.025, -0.025,  0.05 ,  0.05 ,  0.05 ,  0.05 ],
        [-0.175,  0.825, -0.175, -0.175, -0.1  , -0.1  , -0.1  , -0.1  ,
         -0.025, -0.025, -0.025, -0.025,  0.05 ,  0.05 ,  0.05 ,  0.05 ],
        [-0.175, -0.175,  0.825, -0.175, -0.1  , -0.1  , -0.1  , -0.1  ,
         -0.025, -0.025, -0.025, -0.025,  0.05 ,  0.05 ,  0.05 ,  0.05 ],
        [-0.175, -0.175, -0.175,  0.825, -0.1  , -0.1  , -0.1  , -0.1  ,
         -0.025, -0.025, -0.025, -0.025,  0.05 ,  0.05 ,  0.05 ,  0.05 ],
        [-0.1  , -0.1  , -0.1  , -0.1  ,  0.925, -0.075, -0.075, -0.075,
         -0.05 , -0.05 , -0.05 , -0.05 , -0.025, -0.025, -0.025, -0.025],
        [-0.1  , -0.1  , -0.1  , -0.1  , -0.075,  0.925, -0.075, -0.075,
         -0.05 , -0.05 , -0.05 , -0.05 , -0.025, -0.025, -0.025, -0.025],
        [-0.1  , -0.1  , -0.1  , -0.1  , -0.075, -0.075,  0.925, -0.075,
         -0.05 , -0.05 , -0.05 , -0.05 , -0.0